### ISSUE TITLE
Loading jsonld after created() function finished

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [ariesjia/vue-jsonld#19]
So I'm trying to use this plugin for vue but I'm having some trouble loading the data. I have a function to get the product data from an API created() and I want to after loading the data to load the JSON-LD script tag. How can achieve this?

**Comment by ariesjia** [comment]
jsonld can be a function and append to component `computed`. you can try like this

```html
<template>
  ...
</template>

<script>
  export default {
    created() {
       //do fetch
    },
    data() {
      return {
        product: null
      },
    },
    jsonld() {
      return this.product &&  {
         "@context": "http://schema.org/",
         "@type": "Product",
         "name": this.product.name,
         "description": this.product.description,
         "discussionUrl": "xxxx"
      }
    },
  }
</script>
```

**Comment by DEADSEC-SECURITY** [comment]
That worked for me. Thanks for the help!
