### ISSUE TITLE
unclear implementation for vue

### ISSUE THREAD

**Issue by hoseinmirian** [ariesjia/vue-jsonld#22]
it is very difficult to understand how to and where to put those code to make it work. I appreciate reply me with a detailed response.

**Comment by ariesjia** [comment]
Sorry, the document may not be detailed enough.
You can check the demo code here.


First Step use `Vue.use(VueJsonLD)` to install

[https://github.com/ariesjia/vue-jsonld/blob/master/demo/index.js](https://github.com/ariesjia/vue-jsonld/blob/master/demo/index.js)

Then use `jsonld` configuration, demo code like this

[https://github.com/ariesjia/vue-jsonld/blob/master/demo/component2.vue](https://github.com/ariesjia/vue-jsonld/blob/master/demo/component2.vue)

Can this help you，If you have any questions ,feel free to contact me.
